INSERT INTO USUARIO(nome, tipo) VALUES('Jobson Mateus', 'ADMININASTRO');
INSERT INTO USUARIO(nome, tipo) VALUES('Jobson Mateus', 'COORDENADOR');
INSERT INTO USUARIO(nome, tipo) VALUES('Jobson Mateus', 'PROFESSOR');
INSERT INTO USUARIO(nome, tipo) VALUES('Jobson Mateus', 'ALUNO');

INSERT INTO DISCIPLINA(nome) VALUES('A');
INSERT INTO DISCIPLINA(nome) VALUES('B');
INSERT INTO DISCIPLINA(nome) VALUES('C');
INSERT INTO DISCIPLINA(nome) VALUES('D');
INSERT INTO DISCIPLINA(nome) VALUES('E');
INSERT INTO DISCIPLINA(nome) VALUES('F');
INSERT INTO DISCIPLINA(nome) VALUES('G');
INSERT INTO DISCIPLINA(nome) VALUES('H');
INSERT INTO DISCIPLINA(nome) VALUES('I');
INSERT INTO DISCIPLINA(nome) VALUES('J');
INSERT INTO DISCIPLINA(nome) VALUES('K');

INSERT INTO CURSO(nome) VALUES('ENGENHARIA DE COMPUTACAO');
INSERT INTO CURSO(nome) VALUES('CIENCIA DA COMPUTACAO');
INSERT INTO CURSO(nome) VALUES('PSICOLOGIA');